apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ako1
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ako.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: ako1
  selector:
    matchLabels:
      {{- include "ako.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ako.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: ako-sa
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.persistentVolumeClaim }}
      volumes:
      - name: ako-pv-storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          {{ if .Values.persistentVolumeClaim }}
          volumeMounts:
          - mountPath: {{ .Values.mountPath }}
            name: ako-pv-storage-1
          {{ end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","/var/pre_stop_hook.sh"]
          env:
          {{ if .Values.avicredentials.certificateAuthorityData  }}
          - name: CTRL_CA_DATA
            valueFrom:
              secretKeyRef:
                name: avi-secret
                key: certificateAuthorityData
            {{ end }}
          - name: CTRL_IPADDRESS
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: controllerIP
          - name: CTRL_VERSION
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: controllerVersion
          - name: CNI_PLUGIN
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: cniPlugin
          - name: ISTIO_ENABLED
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: istioEnabled
          - name: VIP_PER_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: vipPerNamespace
          - name: SHARD_VS_SIZE
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: shardVSSize
          - name: PASSTHROUGH_SHARD_SIZE
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: passthroughShardSize
          - name: FULL_SYNC_INTERVAL
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: fullSyncFrequency
          - name: CLOUD_NAME
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: cloudName
          - name: TENANT_NAME
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: tenantName
          - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: clusterName
          - name: ENABLE_RHI
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: enableRHI
          - name: ENABLE_EVH
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: enableEVH
          - name: SERVICES_API
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: servicesAPI
          - name: DEFAULT_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: defaultDomain
          - name: DISABLE_STATIC_ROUTE_SYNC
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: disableStaticRouteSync
           {{ if .Values.NetworkSettings.nsxtT1LR }}
          - name: NSXT_T1_LR
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: nsxtT1LR
          {{ end }}
          - name: NAMESPACE_SYNC_LABEL_KEY
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: nsSyncLabelKey
          - name: NAMESPACE_SYNC_LABEL_VALUE
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: nsSyncLabelValue
          - name: DEFAULT_ING_CONTROLLER
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: defaultIngController
          - name: SEG_NAME
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: serviceEngineGroupName
          - name: BGP_PEER_LABELS
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: bgpPeerLabels
          - name: NODE_NETWORK_LIST
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: nodeNetworkList
          - name: VIP_NETWORK_LIST
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: vipNetworkList
          - name: AKO_API_PORT
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: apiServerPort
          - name: SERVICE_TYPE
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: serviceType
          {{ if eq .Values.L7Settings.serviceType "NodePort" }}
          - name: NODE_KEY
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: nodeKey
          - name: NODE_VALUE
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: nodeValue
          {{ end }}
          - name: AUTO_L4_FQDN
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config-1
                key: autoFQDN
          {{ if .Values.persistentVolumeClaim }}
          - name: USE_PVC
            value: "true"
          {{ end }}
          - name: LOG_FILE_PATH
            value: {{ .Values.mountPath }}
          - name: LOG_FILE_NAME
            value: {{ .Values.logFile }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/status
              port:  {{ default "8080" .Values.AKOSettings.apiServerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
